// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// construct_flux_boundaries_fast
List construct_flux_boundaries_fast(NumericVector LB_rep, NumericVector neg_one_vec, NumericVector one_vec, NumericVector ras, LogicalVector rev_indices, LogicalVector non_rev_indices, IntegerVector tail_idx, IntegerVector medium_matches, NumericVector zero_vec_final_s);
RcppExport SEXP _METAFlux2_construct_flux_boundaries_fast(SEXP LB_repSEXP, SEXP neg_one_vecSEXP, SEXP one_vecSEXP, SEXP rasSEXP, SEXP rev_indicesSEXP, SEXP non_rev_indicesSEXP, SEXP tail_idxSEXP, SEXP medium_matchesSEXP, SEXP zero_vec_final_sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type LB_rep(LB_repSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type neg_one_vec(neg_one_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type one_vec(one_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ras(rasSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type rev_indices(rev_indicesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type non_rev_indices(non_rev_indicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type tail_idx(tail_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type medium_matches(medium_matchesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type zero_vec_final_s(zero_vec_final_sSEXP);
    rcpp_result_gen = Rcpp::wrap(construct_flux_boundaries_fast(LB_rep, neg_one_vec, one_vec, ras, rev_indices, non_rev_indices, tail_idx, medium_matches, zero_vec_final_s));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_METAFlux2_construct_flux_boundaries_fast", (DL_FUNC) &_METAFlux2_construct_flux_boundaries_fast, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_METAFlux2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
