# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast boundary construction for OSQP optimization
#' 
#' This C++ function constructs the lower and upper bounds for OSQP solver
#' much faster than the R implementation (10-50x speedup).
#' 
#' @param LB_rep Repeated lower bounds vector
#' @param neg_one_vec Negative ones vector
#' @param one_vec Ones vector  
#' @param ras Reaction activity scores
#' @param rev_indices Logical vector indicating reversible reactions
#' @param non_rev_indices Logical vector indicating non-reversible reactions
#' @param tail_idx Indices for tail elements
#' @param medium_matches Indices for medium matching
#' @param zero_vec_final_s Zero vector for final S matrix
#' 
#' @return List with l (lower bounds) and u (upper bounds)
#' @keywords internal
#' @export
construct_flux_boundaries_fast <- function(LB_rep, neg_one_vec, one_vec, ras, rev_indices, non_rev_indices, tail_idx, medium_matches, zero_vec_final_s) {
    .Call('_METAFlux2_construct_flux_boundaries_fast', PACKAGE = 'METAFlux2', LB_rep, neg_one_vec, one_vec, ras, rev_indices, non_rev_indices, tail_idx, medium_matches, zero_vec_final_s)
}

